const SET_FILTER_REQUEST = 'SET_FILTER_REQUEST';
const SET_FILTER_SUCCESS = 'SET_FILTER_SUCCESS';
const SET_FILTER_ERROR = 'SET_FILTER_ERROR';

export {
    SET_FILTER_REQUEST,
    SET_FILTER_SUCCESS,
    SET_FILTER_ERROR,
};
