const SET_PERCEPTION = 'SET_PERCEPTION';
const SET_PERCEPTION_ERROR = 'SET_PERCEPTION_ERROR';
const SET_THEMES = 'SET_THEMES';
const SET_THEMES_ERROR = 'SET_THEMES_ERROR';
const SET_ATTRIBUTES = 'SET_ATTRIBUTES';
const SET_ATTRIBUTES_ERROR = 'SET_ATTRIBUTES_ERROR';

export {
  SET_PERCEPTION,
  SET_PERCEPTION_ERROR,
  SET_THEMES,
  SET_THEMES_ERROR,
  SET_ATTRIBUTES,
  SET_ATTRIBUTES_ERROR,
};
